### ISSUE TITLE
Replies and Alter Cards

### ISSUE THREAD

**Issue by Firebornsys** [PluralKit/PluralKit#519]
So a while ago, like October, I got our system token from plural kit to connect our SP to our PK yknow? So I dont have to remake all the bots

And it was fine before that and then after that, but in November suddenly alter cards wouldnt show up. If someone used a bot and replied to a message, we can see the message itself but we cant see what it replied to. Its getting annoying now trying to make sure we got things right and cant check. Ill attach an image of what Im talking about.

Also semi related, Im putting this out incase anyone knows about this too, confession bot has also been bugged, we cant see confessions or when we try to confess the servers wont come up

But pls help

![Screenshot_20230203_235553_Discord](https://user-images.githubusercontent.com/124419068/216749562-85ea50ca-bc9d-449f-8c5f-565a246576cb.jpg)
![Screenshot_20230204_000332_Discord](https://user-images.githubusercontent.com/124419068/216749663-bb483d16-4eb6-48cb-bb1a-36dbdeeb9c13.jpg)

**Comment by spiralw** [comment]
you need to enable this option in your discord settings: 

![20230204_00h07m18s_grim](https://user-images.githubusercontent.com/64013111/216749814-8246f118-df41-4db9-a1b7-296f65dbb2a5.png)

in the future, please join the support server to ask for help with the bot. <https://discord.gg/PczBt78>

**Comment by u1f408** [comment]
Hi! This is happening because you have the “display link previews” setting in Discord turned off - this setting here has to be turned on in your Discord app:

![E26EDFEA-FA1F-4E14-B512-2F79958C2052](https://user-images.githubusercontent.com/30218526/216749834-71abe3c8-9b4f-4d3d-94dd-3e1f35cf36c6.jpeg)

In future, please ask support questions about the bot in our Discord server: https://discord.gg/PczBt78
