### ISSUE TITLE
Random Member button shows private members 

### ISSUE THREAD

**Issue by jdax** [PluralKit/PluralKit#560]
When logged in and logged out of the dashboard, hitting "random member" returns private members. I believe the issue stems from line 42 here https://github.com/PluralKit/PluralKit/blob/main/dashboard/src/routes/Dash/Random.svelte

`if (searchParams && searchParams.get("all") === "true") usePrivateItems = true;`

**Comment by greysdawn** [comment]
Is there any way you can give proof of this? The API shouldn't allow private members to show up when fetching lists unless you're logged in, in which case you can only fetch your own private members. The dash uses the API to fetch data, so it shouldn't be possible to pull up private members when logged out since they shouldn't end up in the dataset at all

**Comment by u1f408** [comment]
The API (and therefore the dashboard) doesn't return private members unless authenticated - this is simply a case of "you thought you logged out, but you didn't."
